name: Build APK test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.bubblewrap
          sudo mkdir -p $ANDROID_HOME/tools
          echo "{\"jdkPath\":\"$JAVA_HOME\",\"androidSdkPath\":\"$ANDROID_HOME\"}" > ~/.bubblewrap/config.json
          npm i -g @bubblewrap/cli
          bubblewrap build
