name: Test Android
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$ANDROID_HOME"
      - run: ls -l $ANDROID_HOME
      - run: ls -l $ANDROID_HOME/cmdline-tools/latest/bin
      - run: ls -l /usr/lib/jvm/temurin-17-jdk-amd64
