name: Test SDK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -la /usr/local/lib/android/sdk
          npm i -g @bubblewrap/cli
          echo "{\"jdkPath\":\"$JAVA_HOME\",\"androidSdkPath\":\"$ANDROID_HOME\"}" > ~/.bubblewrap/config.json
          cat ~/.bubblewrap/config.json
          npx @bubblewrap/core android
