name: Test Help
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bubblewrap
        run: npm i -g @bubblewrap/cli

      - name: Check Bubblewrap help
        run: |
          bubblewrap build --help || true
